flowchart TB
  network_management_288965a1f2["Management<br/>192.0.2.0/24<br/>VMware: EXAMPLE_MANAGEMENT_NETWORK<br/>bastion: 192.0.2.10"]
  host_bastion1_fd65cf69ce["bastion1<br/>multi-homed<br/>not a router"]
  network_customer_b6c4586387["Customer<br/>198.51.100.0/28<br/>VMware: EXAMPLE_CUSTOMER_NETWORK<br/>bastion: 198.51.100.4<br/>gateway: 198.51.100.1"]
  host_prom1_abf2e7bd7a["Prometheus host<br/>prom1<br/>198.51.100.6"]
  subgraph cluster_cluster_rke2_rancher_de77c71a50["RKE2 / Rancher"]
    direction TB
    host_rancher1_d47e6b0e07["rancher1 primary<br/>198.51.100.11"]
    host_rancher2_bcc55a020f["rancher2<br/>198.51.100.12"]
    host_rancher3_bbbf0c319b["rancher3<br/>198.51.100.13"]
  end
  subgraph downstream_downstream_vlan565_8ed6786137["VLAN 565"]
    direction TB
    network_downstream_vlan565_8ed6786137["VLAN 565<br/>203.0.113.32/27<br/>VMware: EXAMPLE_DOWNSTREAM_NETWORK_565<br/>bastion: 203.0.113.34"]
    consumer_consumer_downstream_vlan565_dfc74929d4["Downstream nodes<br/>DHCP 203.0.113.36-203.0.113.61<br/>external lifecycle"]
    external_endpoint_gateway_vlan565_97aa5a5c3b["External gateway<br/>203.0.113.33"]
  end
  network_downstream_vlan565_8ed6786137 --- consumer_consumer_downstream_vlan565_dfc74929d4
  network_downstream_vlan565_8ed6786137 --- external_endpoint_gateway_vlan565_97aa5a5c3b
  subgraph downstream_downstream_vlan566_d2bd8ff235["VLAN 566"]
    direction TB
    network_downstream_vlan566_d2bd8ff235["VLAN 566<br/>203.0.113.64/27<br/>VMware: EXAMPLE_DOWNSTREAM_NETWORK_566<br/>bastion: 203.0.113.66"]
    consumer_consumer_downstream_vlan566_30b7d29b35["Downstream nodes<br/>DHCP 203.0.113.68-203.0.113.93<br/>external lifecycle"]
    external_endpoint_gateway_vlan566_8cbaf7cad8["External gateway<br/>203.0.113.65"]
  end
  network_downstream_vlan566_d2bd8ff235 --- consumer_consumer_downstream_vlan566_30b7d29b35
  network_downstream_vlan566_d2bd8ff235 --- external_endpoint_gateway_vlan566_8cbaf7cad8
  host_bastion1_fd65cf69ce --- network_customer_b6c4586387
  network_management_288965a1f2 --- host_bastion1_fd65cf69ce
  network_customer_b6c4586387 --- host_prom1_abf2e7bd7a
  network_customer_b6c4586387 --- host_rancher1_d47e6b0e07
  network_customer_b6c4586387 --- host_rancher2_bcc55a020f
  network_customer_b6c4586387 --- host_rancher3_bbbf0c319b
  host_bastion1_fd65cf69ce --- network_downstream_vlan565_8ed6786137
  host_bastion1_fd65cf69ce --- network_downstream_vlan566_d2bd8ff235
  network_customer_b6c4586387 -. "external routing / firewall" .-> network_downstream_vlan565_8ed6786137
  network_customer_b6c4586387 -. "external routing / firewall" .-> network_downstream_vlan566_d2bd8ff235
